### ISSUE TITLE
please support androidX

### ISSUE THREAD

**Issue by jearyvon** [react-native-community/react-native-viewpager#48]

**Comment by ferrannp** [comment]
I will create a version using Android X by default. For now, you have to use https://github.com/mikehardy/jetifier. If you run `react-native run-android` on RN >= 0.60.x, it should run jetifier for you by default.

**Comment by ElliDy** [comment]
@ferrannp I have problems to bundle my apk in gitlab, because I´m using your library and it does not support AndroidX. I will try now to set the ANDROID_BUILD_TOOLS version to 28.0.2 instead of 28.0.3. Hope that helps. Do you have another solution? I know, that support androidx is not an easy made step, but it would be nice, if you reconsider that.
